#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Inst_JoseCelilioValle")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAlumno(Alumno instance);
    partial void UpdateAlumno(Alumno instance);
    partial void DeleteAlumno(Alumno instance);
    partial void InsertEmpleado(Empleado instance);
    partial void UpdateEmpleado(Empleado instance);
    partial void DeleteEmpleado(Empleado instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertPuesto_Empleado(Puesto_Empleado instance);
    partial void UpdatePuesto_Empleado(Puesto_Empleado instance);
    partial void DeletePuesto_Empleado(Puesto_Empleado instance);
    partial void InsertEncargado(Encargado instance);
    partial void UpdateEncargado(Encargado instance);
    partial void DeleteEncargado(Encargado instance);
    partial void InsertBuses(Buses instance);
    partial void UpdateBuses(Buses instance);
    partial void DeleteBuses(Buses instance);
    partial void InsertRuta(Ruta instance);
    partial void UpdateRuta(Ruta instance);
    partial void DeleteRuta(Ruta instance);
    partial void InsertBoleta_Venta(Boleta_Venta instance);
    partial void UpdateBoleta_Venta(Boleta_Venta instance);
    partial void DeleteBoleta_Venta(Boleta_Venta instance);
    partial void Insertdetalle_boletaVenta(detalle_boletaVenta instance);
    partial void Updatedetalle_boletaVenta(detalle_boletaVenta instance);
    partial void Deletedetalle_boletaVenta(detalle_boletaVenta instance);
    partial void InsertTipo_ServicioPaga(Tipo_ServicioPaga instance);
    partial void UpdateTipo_ServicioPaga(Tipo_ServicioPaga instance);
    partial void DeleteTipo_ServicioPaga(Tipo_ServicioPaga instance);
    partial void InsertForma_Pago(Forma_Pago instance);
    partial void UpdateForma_Pago(Forma_Pago instance);
    partial void DeleteForma_Pago(Forma_Pago instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApplication1.Properties.Settings.Default.Inst_JoseCelilioValleConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alumno> Alumno
		{
			get
			{
				return this.GetTable<Alumno>();
			}
		}
		
		public System.Data.Linq.Table<Empleado> Empleado
		{
			get
			{
				return this.GetTable<Empleado>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estado
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<Puesto_Empleado> Puesto_Empleado
		{
			get
			{
				return this.GetTable<Puesto_Empleado>();
			}
		}
		
		public System.Data.Linq.Table<alumno_encargado> alumno_encargado
		{
			get
			{
				return this.GetTable<alumno_encargado>();
			}
		}
		
		public System.Data.Linq.Table<Encargado> Encargado
		{
			get
			{
				return this.GetTable<Encargado>();
			}
		}
		
		public System.Data.Linq.Table<Buses> Buses
		{
			get
			{
				return this.GetTable<Buses>();
			}
		}
		
		public System.Data.Linq.Table<Ruta> Ruta
		{
			get
			{
				return this.GetTable<Ruta>();
			}
		}
		
		public System.Data.Linq.Table<Boleta_Venta> Boleta_Venta
		{
			get
			{
				return this.GetTable<Boleta_Venta>();
			}
		}
		
		public System.Data.Linq.Table<detalle_boletaVenta> detalle_boletaVenta
		{
			get
			{
				return this.GetTable<detalle_boletaVenta>();
			}
		}
		
		public System.Data.Linq.Table<Tipo_ServicioPaga> Tipo_ServicioPaga
		{
			get
			{
				return this.GetTable<Tipo_ServicioPaga>();
			}
		}
		
		public System.Data.Linq.Table<Forma_Pago> Forma_Pago
		{
			get
			{
				return this.GetTable<Forma_Pago>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarMatriculaTraslado")]
		public int ActualizarMatriculaTraslado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string instituto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string retrasada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tpa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, instituto, retrasada, tpa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarPeriodoGrado")]
		public int ActualizarPeriodoGrado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, descripcion, grado, seccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarEncargado")]
		public int ingresarEncargado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idEncargado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreEncargado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lugarTrabajo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEncargado, nombreEncargado, lugarTrabajo, telefono, celular, email, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarEncargado2")]
		public int ingresarEncargado2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idEncargado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreEncargado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lugarTrabajo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEncargado, nombreEncargado, lugarTrabajo, telefono, celular, email, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarAlumnoEncargado")]
		public int insertarAlumnoEncargado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarIDruta")]
		public int insertarIDruta()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarruta")]
		public int insertarruta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarbuses")]
		public int insertarbuses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ruta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoE, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> numbus, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string placaB)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), estado, ruta, codigoE, numbus, placaB);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarAlumnoEncargado2")]
		public int insertarAlumnoEncargado2()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarAlumnos")]
		public int ingresarAlumnos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string idAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombreAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fechaNac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string direccionAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string lugarNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string generoAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string telefonoAlumno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string cursoInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string instituto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string materiaRetrasada, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string materiaTPA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAlumno, nombreAlumno, codigoEstado, fechaNac, direccionAlumno, lugarNacimiento, generoAlumno, telefonoAlumno, cursoInicial, instituto, materiaRetrasada, materiaTPA);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarPeriodosGrados")]
		public int ingresarPeriodosGrados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> grado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> seccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> aula)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, grado, seccion, aula);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarGradoAlumno")]
		public int insertarGradoAlumno()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EX_estado")]
		public int EX_estado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EST", DbType="Int")] System.Nullable<int> eST, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usr", DbType="VarChar(50)")] string usr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eST, usr);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ingresarEmpleados")]
		public int ingresarEmpleados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string idEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string nombreEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigopuestoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigoEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string correoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string telefonoEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string telefonoEmergenciaEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string direccionEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string usuarioEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(MAX)")] string contraseñaEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado, nombreEmpleado, codigopuestoEmpleado, codigoEstado, correoEmpleado, telefonoEmpleado, telefonoEmergenciaEmpleado, direccionEmpleado, usuarioEmpleado, contraseñaEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.modificarPrecio")]
		public int modificarPrecio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> precio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, precio);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alumno")]
	public partial class Alumno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_alumno;
		
		private int _codigo_estado;
		
		private string _id_alumno;
		
		private string _nombre_alumno;
		
		private string _direccion_alumno;
		
		private string _fechaNac_alumno;
		
		private string _genero_alumno;
		
		private string _telefono_alumno;
		
		private string _curso_iniciado;
		
		private string _instituto_procedencia;
		
		private string _lugarNacimiento_alumno;
		
		private string _materiaRetrasada;
		
		private string _materiaTPA;
		
		private EntitySet<detalle_boletaVenta> _detalle_boletaVenta;
		
		private EntityRef<Estado> _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_alumnoChanging(int value);
    partial void Oncodigo_alumnoChanged();
    partial void Oncodigo_estadoChanging(int value);
    partial void Oncodigo_estadoChanged();
    partial void Onid_alumnoChanging(string value);
    partial void Onid_alumnoChanged();
    partial void Onnombre_alumnoChanging(string value);
    partial void Onnombre_alumnoChanged();
    partial void Ondireccion_alumnoChanging(string value);
    partial void Ondireccion_alumnoChanged();
    partial void OnfechaNac_alumnoChanging(string value);
    partial void OnfechaNac_alumnoChanged();
    partial void Ongenero_alumnoChanging(string value);
    partial void Ongenero_alumnoChanged();
    partial void Ontelefono_alumnoChanging(string value);
    partial void Ontelefono_alumnoChanged();
    partial void Oncurso_iniciadoChanging(string value);
    partial void Oncurso_iniciadoChanged();
    partial void Oninstituto_procedenciaChanging(string value);
    partial void Oninstituto_procedenciaChanged();
    partial void OnlugarNacimiento_alumnoChanging(string value);
    partial void OnlugarNacimiento_alumnoChanged();
    partial void OnmateriaRetrasadaChanging(string value);
    partial void OnmateriaRetrasadaChanged();
    partial void OnmateriaTPAChanging(string value);
    partial void OnmateriaTPAChanged();
    #endregion
		
		public Alumno()
		{
			this._detalle_boletaVenta = new EntitySet<detalle_boletaVenta>(new Action<detalle_boletaVenta>(this.attach_detalle_boletaVenta), new Action<detalle_boletaVenta>(this.detach_detalle_boletaVenta));
			this._Estado = default(EntityRef<Estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_alumno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_alumno
		{
			get
			{
				return this._codigo_alumno;
			}
			set
			{
				if ((this._codigo_alumno != value))
				{
					this.Oncodigo_alumnoChanging(value);
					this.SendPropertyChanging();
					this._codigo_alumno = value;
					this.SendPropertyChanged("codigo_alumno");
					this.Oncodigo_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_estado", DbType="Int NOT NULL")]
		public int codigo_estado
		{
			get
			{
				return this._codigo_estado;
			}
			set
			{
				if ((this._codigo_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_estadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_estado = value;
					this.SendPropertyChanged("codigo_estado");
					this.Oncodigo_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_alumno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string id_alumno
		{
			get
			{
				return this._id_alumno;
			}
			set
			{
				if ((this._id_alumno != value))
				{
					this.Onid_alumnoChanging(value);
					this.SendPropertyChanging();
					this._id_alumno = value;
					this.SendPropertyChanged("id_alumno");
					this.Onid_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_alumno", DbType="VarChar(50)")]
		public string nombre_alumno
		{
			get
			{
				return this._nombre_alumno;
			}
			set
			{
				if ((this._nombre_alumno != value))
				{
					this.Onnombre_alumnoChanging(value);
					this.SendPropertyChanging();
					this._nombre_alumno = value;
					this.SendPropertyChanged("nombre_alumno");
					this.Onnombre_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_alumno", DbType="VarChar(50)")]
		public string direccion_alumno
		{
			get
			{
				return this._direccion_alumno;
			}
			set
			{
				if ((this._direccion_alumno != value))
				{
					this.Ondireccion_alumnoChanging(value);
					this.SendPropertyChanging();
					this._direccion_alumno = value;
					this.SendPropertyChanged("direccion_alumno");
					this.Ondireccion_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNac_alumno", DbType="VarChar(50)")]
		public string fechaNac_alumno
		{
			get
			{
				return this._fechaNac_alumno;
			}
			set
			{
				if ((this._fechaNac_alumno != value))
				{
					this.OnfechaNac_alumnoChanging(value);
					this.SendPropertyChanging();
					this._fechaNac_alumno = value;
					this.SendPropertyChanged("fechaNac_alumno");
					this.OnfechaNac_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero_alumno", DbType="VarChar(1)")]
		public string genero_alumno
		{
			get
			{
				return this._genero_alumno;
			}
			set
			{
				if ((this._genero_alumno != value))
				{
					this.Ongenero_alumnoChanging(value);
					this.SendPropertyChanging();
					this._genero_alumno = value;
					this.SendPropertyChanged("genero_alumno");
					this.Ongenero_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_alumno", DbType="VarChar(10)")]
		public string telefono_alumno
		{
			get
			{
				return this._telefono_alumno;
			}
			set
			{
				if ((this._telefono_alumno != value))
				{
					this.Ontelefono_alumnoChanging(value);
					this.SendPropertyChanging();
					this._telefono_alumno = value;
					this.SendPropertyChanged("telefono_alumno");
					this.Ontelefono_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_iniciado", DbType="VarChar(20)")]
		public string curso_iniciado
		{
			get
			{
				return this._curso_iniciado;
			}
			set
			{
				if ((this._curso_iniciado != value))
				{
					this.Oncurso_iniciadoChanging(value);
					this.SendPropertyChanging();
					this._curso_iniciado = value;
					this.SendPropertyChanged("curso_iniciado");
					this.Oncurso_iniciadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instituto_procedencia", DbType="VarChar(50)")]
		public string instituto_procedencia
		{
			get
			{
				return this._instituto_procedencia;
			}
			set
			{
				if ((this._instituto_procedencia != value))
				{
					this.Oninstituto_procedenciaChanging(value);
					this.SendPropertyChanging();
					this._instituto_procedencia = value;
					this.SendPropertyChanged("instituto_procedencia");
					this.Oninstituto_procedenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugarNacimiento_alumno", DbType="VarChar(50)")]
		public string lugarNacimiento_alumno
		{
			get
			{
				return this._lugarNacimiento_alumno;
			}
			set
			{
				if ((this._lugarNacimiento_alumno != value))
				{
					this.OnlugarNacimiento_alumnoChanging(value);
					this.SendPropertyChanging();
					this._lugarNacimiento_alumno = value;
					this.SendPropertyChanged("lugarNacimiento_alumno");
					this.OnlugarNacimiento_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materiaRetrasada", DbType="VarChar(50)")]
		public string materiaRetrasada
		{
			get
			{
				return this._materiaRetrasada;
			}
			set
			{
				if ((this._materiaRetrasada != value))
				{
					this.OnmateriaRetrasadaChanging(value);
					this.SendPropertyChanging();
					this._materiaRetrasada = value;
					this.SendPropertyChanged("materiaRetrasada");
					this.OnmateriaRetrasadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materiaTPA", DbType="VarChar(50)")]
		public string materiaTPA
		{
			get
			{
				return this._materiaTPA;
			}
			set
			{
				if ((this._materiaTPA != value))
				{
					this.OnmateriaTPAChanging(value);
					this.SendPropertyChanging();
					this._materiaTPA = value;
					this.SendPropertyChanged("materiaTPA");
					this.OnmateriaTPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_detalle_boletaVenta", Storage="_detalle_boletaVenta", ThisKey="codigo_alumno", OtherKey="codigo_alumno")]
		public EntitySet<detalle_boletaVenta> detalle_boletaVenta
		{
			get
			{
				return this._detalle_boletaVenta;
			}
			set
			{
				this._detalle_boletaVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Alumno", Storage="_Estado", ThisKey="codigo_estado", OtherKey="codigo_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Alumno.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Alumno.Add(this);
						this._codigo_estado = value.codigo_estado;
					}
					else
					{
						this._codigo_estado = default(int);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = this;
		}
		
		private void detach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Alumno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empleado")]
	public partial class Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_empleado;
		
		private System.Nullable<int> _codigo_puestoEmpleado;
		
		private System.Nullable<int> _codigo_estado;
		
		private System.Nullable<int> _id_empleado;
		
		private string _nombre_empleado;
		
		private string _telefono_empleado;
		
		private string _telefono_emplaedoEmergencia;
		
		private string _email_empleado;
		
		private string _direccion_empleado;
		
		private string _usr_empleado;
		
		private string _pwd_empleado;
		
		private EntitySet<Buses> _Buses;
		
		private EntitySet<Boleta_Venta> _Boleta_Venta;
		
		private EntityRef<Estado> _Estado;
		
		private EntityRef<Puesto_Empleado> _Puesto_Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_empleadoChanging(int value);
    partial void Oncodigo_empleadoChanged();
    partial void Oncodigo_puestoEmpleadoChanging(System.Nullable<int> value);
    partial void Oncodigo_puestoEmpleadoChanged();
    partial void Oncodigo_estadoChanging(System.Nullable<int> value);
    partial void Oncodigo_estadoChanged();
    partial void Onid_empleadoChanging(System.Nullable<int> value);
    partial void Onid_empleadoChanged();
    partial void Onnombre_empleadoChanging(string value);
    partial void Onnombre_empleadoChanged();
    partial void Ontelefono_empleadoChanging(string value);
    partial void Ontelefono_empleadoChanged();
    partial void Ontelefono_emplaedoEmergenciaChanging(string value);
    partial void Ontelefono_emplaedoEmergenciaChanged();
    partial void Onemail_empleadoChanging(string value);
    partial void Onemail_empleadoChanged();
    partial void Ondireccion_empleadoChanging(string value);
    partial void Ondireccion_empleadoChanged();
    partial void Onusr_empleadoChanging(string value);
    partial void Onusr_empleadoChanged();
    partial void Onpwd_empleadoChanging(string value);
    partial void Onpwd_empleadoChanged();
    #endregion
		
		public Empleado()
		{
			this._Buses = new EntitySet<Buses>(new Action<Buses>(this.attach_Buses), new Action<Buses>(this.detach_Buses));
			this._Boleta_Venta = new EntitySet<Boleta_Venta>(new Action<Boleta_Venta>(this.attach_Boleta_Venta), new Action<Boleta_Venta>(this.detach_Boleta_Venta));
			this._Estado = default(EntityRef<Estado>);
			this._Puesto_Empleado = default(EntityRef<Puesto_Empleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_empleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_empleado
		{
			get
			{
				return this._codigo_empleado;
			}
			set
			{
				if ((this._codigo_empleado != value))
				{
					this.Oncodigo_empleadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_empleado = value;
					this.SendPropertyChanged("codigo_empleado");
					this.Oncodigo_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_puestoEmpleado", DbType="Int")]
		public System.Nullable<int> codigo_puestoEmpleado
		{
			get
			{
				return this._codigo_puestoEmpleado;
			}
			set
			{
				if ((this._codigo_puestoEmpleado != value))
				{
					if (this._Puesto_Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_puestoEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_puestoEmpleado = value;
					this.SendPropertyChanged("codigo_puestoEmpleado");
					this.Oncodigo_puestoEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_estado", DbType="Int")]
		public System.Nullable<int> codigo_estado
		{
			get
			{
				return this._codigo_estado;
			}
			set
			{
				if ((this._codigo_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_estadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_estado = value;
					this.SendPropertyChanged("codigo_estado");
					this.Oncodigo_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_empleado", DbType="Int")]
		public System.Nullable<int> id_empleado
		{
			get
			{
				return this._id_empleado;
			}
			set
			{
				if ((this._id_empleado != value))
				{
					this.Onid_empleadoChanging(value);
					this.SendPropertyChanging();
					this._id_empleado = value;
					this.SendPropertyChanged("id_empleado");
					this.Onid_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_empleado", DbType="VarChar(50)")]
		public string nombre_empleado
		{
			get
			{
				return this._nombre_empleado;
			}
			set
			{
				if ((this._nombre_empleado != value))
				{
					this.Onnombre_empleadoChanging(value);
					this.SendPropertyChanging();
					this._nombre_empleado = value;
					this.SendPropertyChanged("nombre_empleado");
					this.Onnombre_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_empleado", DbType="VarChar(10)")]
		public string telefono_empleado
		{
			get
			{
				return this._telefono_empleado;
			}
			set
			{
				if ((this._telefono_empleado != value))
				{
					this.Ontelefono_empleadoChanging(value);
					this.SendPropertyChanging();
					this._telefono_empleado = value;
					this.SendPropertyChanged("telefono_empleado");
					this.Ontelefono_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_emplaedoEmergencia", DbType="VarChar(10)")]
		public string telefono_emplaedoEmergencia
		{
			get
			{
				return this._telefono_emplaedoEmergencia;
			}
			set
			{
				if ((this._telefono_emplaedoEmergencia != value))
				{
					this.Ontelefono_emplaedoEmergenciaChanging(value);
					this.SendPropertyChanging();
					this._telefono_emplaedoEmergencia = value;
					this.SendPropertyChanged("telefono_emplaedoEmergencia");
					this.Ontelefono_emplaedoEmergenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_empleado", DbType="VarChar(50)")]
		public string email_empleado
		{
			get
			{
				return this._email_empleado;
			}
			set
			{
				if ((this._email_empleado != value))
				{
					this.Onemail_empleadoChanging(value);
					this.SendPropertyChanging();
					this._email_empleado = value;
					this.SendPropertyChanged("email_empleado");
					this.Onemail_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_empleado", DbType="VarChar(50)")]
		public string direccion_empleado
		{
			get
			{
				return this._direccion_empleado;
			}
			set
			{
				if ((this._direccion_empleado != value))
				{
					this.Ondireccion_empleadoChanging(value);
					this.SendPropertyChanging();
					this._direccion_empleado = value;
					this.SendPropertyChanged("direccion_empleado");
					this.Ondireccion_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_empleado", DbType="NChar(30)")]
		public string usr_empleado
		{
			get
			{
				return this._usr_empleado;
			}
			set
			{
				if ((this._usr_empleado != value))
				{
					this.Onusr_empleadoChanging(value);
					this.SendPropertyChanging();
					this._usr_empleado = value;
					this.SendPropertyChanged("usr_empleado");
					this.Onusr_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pwd_empleado", DbType="NChar(100)")]
		public string pwd_empleado
		{
			get
			{
				return this._pwd_empleado;
			}
			set
			{
				if ((this._pwd_empleado != value))
				{
					this.Onpwd_empleadoChanging(value);
					this.SendPropertyChanging();
					this._pwd_empleado = value;
					this.SendPropertyChanged("pwd_empleado");
					this.Onpwd_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Buses", Storage="_Buses", ThisKey="codigo_empleado", OtherKey="codigo_empleado")]
		public EntitySet<Buses> Buses
		{
			get
			{
				return this._Buses;
			}
			set
			{
				this._Buses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Boleta_Venta", Storage="_Boleta_Venta", ThisKey="codigo_empleado", OtherKey="codigo_empleado")]
		public EntitySet<Boleta_Venta> Boleta_Venta
		{
			get
			{
				return this._Boleta_Venta;
			}
			set
			{
				this._Boleta_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Empleado", Storage="_Estado", ThisKey="codigo_estado", OtherKey="codigo_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Empleado.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Empleado.Add(this);
						this._codigo_estado = value.codigo_estado;
					}
					else
					{
						this._codigo_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Puesto_Empleado_Empleado", Storage="_Puesto_Empleado", ThisKey="codigo_puestoEmpleado", OtherKey="codigo_puestoEmpleado", IsForeignKey=true)]
		public Puesto_Empleado Puesto_Empleado
		{
			get
			{
				return this._Puesto_Empleado.Entity;
			}
			set
			{
				Puesto_Empleado previousValue = this._Puesto_Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Puesto_Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Puesto_Empleado.Entity = null;
						previousValue.Empleado.Remove(this);
					}
					this._Puesto_Empleado.Entity = value;
					if ((value != null))
					{
						value.Empleado.Add(this);
						this._codigo_puestoEmpleado = value.codigo_puestoEmpleado;
					}
					else
					{
						this._codigo_puestoEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Puesto_Empleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
		
		private void attach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = this;
		}
		
		private void detach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_estado;
		
		private string _descripcion_estado;
		
		private EntitySet<Alumno> _Alumno;
		
		private EntitySet<Empleado> _Empleado;
		
		private EntitySet<Buses> _Buses;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_estadoChanging(int value);
    partial void Oncodigo_estadoChanged();
    partial void Ondescripcion_estadoChanging(string value);
    partial void Ondescripcion_estadoChanged();
    #endregion
		
		public Estado()
		{
			this._Alumno = new EntitySet<Alumno>(new Action<Alumno>(this.attach_Alumno), new Action<Alumno>(this.detach_Alumno));
			this._Empleado = new EntitySet<Empleado>(new Action<Empleado>(this.attach_Empleado), new Action<Empleado>(this.detach_Empleado));
			this._Buses = new EntitySet<Buses>(new Action<Buses>(this.attach_Buses), new Action<Buses>(this.detach_Buses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_estado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_estado
		{
			get
			{
				return this._codigo_estado;
			}
			set
			{
				if ((this._codigo_estado != value))
				{
					this.Oncodigo_estadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_estado = value;
					this.SendPropertyChanged("codigo_estado");
					this.Oncodigo_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_estado", DbType="VarChar(20)")]
		public string descripcion_estado
		{
			get
			{
				return this._descripcion_estado;
			}
			set
			{
				if ((this._descripcion_estado != value))
				{
					this.Ondescripcion_estadoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_estado = value;
					this.SendPropertyChanged("descripcion_estado");
					this.Ondescripcion_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Alumno", Storage="_Alumno", ThisKey="codigo_estado", OtherKey="codigo_estado")]
		public EntitySet<Alumno> Alumno
		{
			get
			{
				return this._Alumno;
			}
			set
			{
				this._Alumno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Empleado", Storage="_Empleado", ThisKey="codigo_estado", OtherKey="codigo_estado")]
		public EntitySet<Empleado> Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				this._Empleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Buses", Storage="_Buses", ThisKey="codigo_estado", OtherKey="codigo_estado")]
		public EntitySet<Buses> Buses
		{
			get
			{
				return this._Buses;
			}
			set
			{
				this._Buses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Alumno(Alumno entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
		
		private void attach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
		
		private void attach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Puesto_Empleado")]
	public partial class Puesto_Empleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_puestoEmpleado;
		
		private string _descripcion_puestoEmpleado;
		
		private EntitySet<Empleado> _Empleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_puestoEmpleadoChanging(int value);
    partial void Oncodigo_puestoEmpleadoChanged();
    partial void Ondescripcion_puestoEmpleadoChanging(string value);
    partial void Ondescripcion_puestoEmpleadoChanged();
    #endregion
		
		public Puesto_Empleado()
		{
			this._Empleado = new EntitySet<Empleado>(new Action<Empleado>(this.attach_Empleado), new Action<Empleado>(this.detach_Empleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_puestoEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_puestoEmpleado
		{
			get
			{
				return this._codigo_puestoEmpleado;
			}
			set
			{
				if ((this._codigo_puestoEmpleado != value))
				{
					this.Oncodigo_puestoEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_puestoEmpleado = value;
					this.SendPropertyChanged("codigo_puestoEmpleado");
					this.Oncodigo_puestoEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_puestoEmpleado", DbType="VarChar(50)")]
		public string descripcion_puestoEmpleado
		{
			get
			{
				return this._descripcion_puestoEmpleado;
			}
			set
			{
				if ((this._descripcion_puestoEmpleado != value))
				{
					this.Ondescripcion_puestoEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_puestoEmpleado = value;
					this.SendPropertyChanged("descripcion_puestoEmpleado");
					this.Ondescripcion_puestoEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Puesto_Empleado_Empleado", Storage="_Empleado", ThisKey="codigo_puestoEmpleado", OtherKey="codigo_puestoEmpleado")]
		public EntitySet<Empleado> Empleado
		{
			get
			{
				return this._Empleado;
			}
			set
			{
				this._Empleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Puesto_Empleado = this;
		}
		
		private void detach_Empleado(Empleado entity)
		{
			this.SendPropertyChanging();
			entity.Puesto_Empleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.alumno_encargado")]
	public partial class alumno_encargado
	{
		
		private System.Nullable<int> _codigo_alumno;
		
		private System.Nullable<int> _codigo_encargado;
		
		public alumno_encargado()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_alumno", DbType="Int")]
		public System.Nullable<int> codigo_alumno
		{
			get
			{
				return this._codigo_alumno;
			}
			set
			{
				if ((this._codigo_alumno != value))
				{
					this._codigo_alumno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_encargado", DbType="Int")]
		public System.Nullable<int> codigo_encargado
		{
			get
			{
				return this._codigo_encargado;
			}
			set
			{
				if ((this._codigo_encargado != value))
				{
					this._codigo_encargado = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Encargado")]
	public partial class Encargado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_encargado;
		
		private string _id_encargado;
		
		private string _nombre_encargado;
		
		private string _lugar_trabajo;
		
		private string _telefono_encargado;
		
		private string _celular_encargado;
		
		private string _email_encargado;
		
		private string _direccion_encargado;
		
		private EntitySet<Boleta_Venta> _Boleta_Venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_encargadoChanging(int value);
    partial void Oncodigo_encargadoChanged();
    partial void Onid_encargadoChanging(string value);
    partial void Onid_encargadoChanged();
    partial void Onnombre_encargadoChanging(string value);
    partial void Onnombre_encargadoChanged();
    partial void Onlugar_trabajoChanging(string value);
    partial void Onlugar_trabajoChanged();
    partial void Ontelefono_encargadoChanging(string value);
    partial void Ontelefono_encargadoChanged();
    partial void Oncelular_encargadoChanging(string value);
    partial void Oncelular_encargadoChanged();
    partial void Onemail_encargadoChanging(string value);
    partial void Onemail_encargadoChanged();
    partial void Ondireccion_encargadoChanging(string value);
    partial void Ondireccion_encargadoChanged();
    #endregion
		
		public Encargado()
		{
			this._Boleta_Venta = new EntitySet<Boleta_Venta>(new Action<Boleta_Venta>(this.attach_Boleta_Venta), new Action<Boleta_Venta>(this.detach_Boleta_Venta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_encargado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_encargado
		{
			get
			{
				return this._codigo_encargado;
			}
			set
			{
				if ((this._codigo_encargado != value))
				{
					this.Oncodigo_encargadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_encargado = value;
					this.SendPropertyChanged("codigo_encargado");
					this.Oncodigo_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_encargado", DbType="VarChar(50)")]
		public string id_encargado
		{
			get
			{
				return this._id_encargado;
			}
			set
			{
				if ((this._id_encargado != value))
				{
					this.Onid_encargadoChanging(value);
					this.SendPropertyChanging();
					this._id_encargado = value;
					this.SendPropertyChanged("id_encargado");
					this.Onid_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_encargado", DbType="VarChar(50)")]
		public string nombre_encargado
		{
			get
			{
				return this._nombre_encargado;
			}
			set
			{
				if ((this._nombre_encargado != value))
				{
					this.Onnombre_encargadoChanging(value);
					this.SendPropertyChanging();
					this._nombre_encargado = value;
					this.SendPropertyChanged("nombre_encargado");
					this.Onnombre_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugar_trabajo", DbType="VarChar(50)")]
		public string lugar_trabajo
		{
			get
			{
				return this._lugar_trabajo;
			}
			set
			{
				if ((this._lugar_trabajo != value))
				{
					this.Onlugar_trabajoChanging(value);
					this.SendPropertyChanging();
					this._lugar_trabajo = value;
					this.SendPropertyChanged("lugar_trabajo");
					this.Onlugar_trabajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_encargado", DbType="VarChar(10)")]
		public string telefono_encargado
		{
			get
			{
				return this._telefono_encargado;
			}
			set
			{
				if ((this._telefono_encargado != value))
				{
					this.Ontelefono_encargadoChanging(value);
					this.SendPropertyChanging();
					this._telefono_encargado = value;
					this.SendPropertyChanged("telefono_encargado");
					this.Ontelefono_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular_encargado", DbType="VarChar(10)")]
		public string celular_encargado
		{
			get
			{
				return this._celular_encargado;
			}
			set
			{
				if ((this._celular_encargado != value))
				{
					this.Oncelular_encargadoChanging(value);
					this.SendPropertyChanging();
					this._celular_encargado = value;
					this.SendPropertyChanged("celular_encargado");
					this.Oncelular_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_encargado", DbType="VarChar(50)")]
		public string email_encargado
		{
			get
			{
				return this._email_encargado;
			}
			set
			{
				if ((this._email_encargado != value))
				{
					this.Onemail_encargadoChanging(value);
					this.SendPropertyChanging();
					this._email_encargado = value;
					this.SendPropertyChanged("email_encargado");
					this.Onemail_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_encargado", DbType="VarChar(50)")]
		public string direccion_encargado
		{
			get
			{
				return this._direccion_encargado;
			}
			set
			{
				if ((this._direccion_encargado != value))
				{
					this.Ondireccion_encargadoChanging(value);
					this.SendPropertyChanging();
					this._direccion_encargado = value;
					this.SendPropertyChanged("direccion_encargado");
					this.Ondireccion_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encargado_Boleta_Venta", Storage="_Boleta_Venta", ThisKey="codigo_encargado", OtherKey="codigo_encargado")]
		public EntitySet<Boleta_Venta> Boleta_Venta
		{
			get
			{
				return this._Boleta_Venta;
			}
			set
			{
				this._Boleta_Venta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Encargado = this;
		}
		
		private void detach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Encargado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buses")]
	public partial class Buses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_bus;
		
		private System.Nullable<int> _codigo_estado;
		
		private System.Nullable<int> _codigo_ruta;
		
		private System.Nullable<int> _codigo_empleado;
		
		private System.Nullable<int> _numero_bus;
		
		private string _placa_bus;
		
		private EntityRef<Empleado> _Empleado;
		
		private EntityRef<Estado> _Estado;
		
		private EntityRef<Ruta> _Ruta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_busChanging(int value);
    partial void Oncodigo_busChanged();
    partial void Oncodigo_estadoChanging(System.Nullable<int> value);
    partial void Oncodigo_estadoChanged();
    partial void Oncodigo_rutaChanging(System.Nullable<int> value);
    partial void Oncodigo_rutaChanged();
    partial void Oncodigo_empleadoChanging(System.Nullable<int> value);
    partial void Oncodigo_empleadoChanged();
    partial void Onnumero_busChanging(System.Nullable<int> value);
    partial void Onnumero_busChanged();
    partial void Onplaca_busChanging(string value);
    partial void Onplaca_busChanged();
    #endregion
		
		public Buses()
		{
			this._Empleado = default(EntityRef<Empleado>);
			this._Estado = default(EntityRef<Estado>);
			this._Ruta = default(EntityRef<Ruta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_bus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_bus
		{
			get
			{
				return this._codigo_bus;
			}
			set
			{
				if ((this._codigo_bus != value))
				{
					this.Oncodigo_busChanging(value);
					this.SendPropertyChanging();
					this._codigo_bus = value;
					this.SendPropertyChanged("codigo_bus");
					this.Oncodigo_busChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_estado", DbType="Int")]
		public System.Nullable<int> codigo_estado
		{
			get
			{
				return this._codigo_estado;
			}
			set
			{
				if ((this._codigo_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_estadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_estado = value;
					this.SendPropertyChanged("codigo_estado");
					this.Oncodigo_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ruta", DbType="Int")]
		public System.Nullable<int> codigo_ruta
		{
			get
			{
				return this._codigo_ruta;
			}
			set
			{
				if ((this._codigo_ruta != value))
				{
					if (this._Ruta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_rutaChanging(value);
					this.SendPropertyChanging();
					this._codigo_ruta = value;
					this.SendPropertyChanged("codigo_ruta");
					this.Oncodigo_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_empleado", DbType="Int")]
		public System.Nullable<int> codigo_empleado
		{
			get
			{
				return this._codigo_empleado;
			}
			set
			{
				if ((this._codigo_empleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_empleadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_empleado = value;
					this.SendPropertyChanged("codigo_empleado");
					this.Oncodigo_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero_bus", DbType="Int")]
		public System.Nullable<int> numero_bus
		{
			get
			{
				return this._numero_bus;
			}
			set
			{
				if ((this._numero_bus != value))
				{
					this.Onnumero_busChanging(value);
					this.SendPropertyChanging();
					this._numero_bus = value;
					this.SendPropertyChanged("numero_bus");
					this.Onnumero_busChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa_bus", DbType="VarChar(20)")]
		public string placa_bus
		{
			get
			{
				return this._placa_bus;
			}
			set
			{
				if ((this._placa_bus != value))
				{
					this.Onplaca_busChanging(value);
					this.SendPropertyChanging();
					this._placa_bus = value;
					this.SendPropertyChanged("placa_bus");
					this.Onplaca_busChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Buses", Storage="_Empleado", ThisKey="codigo_empleado", OtherKey="codigo_empleado", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Buses.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Buses.Add(this);
						this._codigo_empleado = value.codigo_empleado;
					}
					else
					{
						this._codigo_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_Buses", Storage="_Estado", ThisKey="codigo_estado", OtherKey="codigo_estado", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.Buses.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.Buses.Add(this);
						this._codigo_estado = value.codigo_estado;
					}
					else
					{
						this._codigo_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Buses", Storage="_Ruta", ThisKey="codigo_ruta", OtherKey="codigo_ruta", IsForeignKey=true)]
		public Ruta Ruta
		{
			get
			{
				return this._Ruta.Entity;
			}
			set
			{
				Ruta previousValue = this._Ruta.Entity;
				if (((previousValue != value) 
							|| (this._Ruta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ruta.Entity = null;
						previousValue.Buses.Remove(this);
					}
					this._Ruta.Entity = value;
					if ((value != null))
					{
						value.Buses.Add(this);
						this._codigo_ruta = value.codigo_ruta;
					}
					else
					{
						this._codigo_ruta = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ruta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ruta")]
	public partial class Ruta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_ruta;
		
		private string _descripcion_ruta;
		
		private EntitySet<Buses> _Buses;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_rutaChanging(int value);
    partial void Oncodigo_rutaChanged();
    partial void Ondescripcion_rutaChanging(string value);
    partial void Ondescripcion_rutaChanged();
    #endregion
		
		public Ruta()
		{
			this._Buses = new EntitySet<Buses>(new Action<Buses>(this.attach_Buses), new Action<Buses>(this.detach_Buses));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_ruta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_ruta
		{
			get
			{
				return this._codigo_ruta;
			}
			set
			{
				if ((this._codigo_ruta != value))
				{
					this.Oncodigo_rutaChanging(value);
					this.SendPropertyChanging();
					this._codigo_ruta = value;
					this.SendPropertyChanged("codigo_ruta");
					this.Oncodigo_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_ruta", DbType="VarChar(50)")]
		public string descripcion_ruta
		{
			get
			{
				return this._descripcion_ruta;
			}
			set
			{
				if ((this._descripcion_ruta != value))
				{
					this.Ondescripcion_rutaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_ruta = value;
					this.SendPropertyChanged("descripcion_ruta");
					this.Ondescripcion_rutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ruta_Buses", Storage="_Buses", ThisKey="codigo_ruta", OtherKey="codigo_ruta")]
		public EntitySet<Buses> Buses
		{
			get
			{
				return this._Buses;
			}
			set
			{
				this._Buses.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = this;
		}
		
		private void detach_Buses(Buses entity)
		{
			this.SendPropertyChanging();
			entity.Ruta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Boleta_Venta")]
	public partial class Boleta_Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_boletaVenta;
		
		private System.Nullable<int> _codigo_encargado;
		
		private System.Nullable<int> _codigo_formaPago;
		
		private System.Nullable<int> _codigo_empleado;
		
		private System.Nullable<System.DateTime> _fecha_boletaVenta;
		
		private string _rtn;
		
		private EntitySet<detalle_boletaVenta> _detalle_boletaVenta;
		
		private EntityRef<Encargado> _Encargado;
		
		private EntityRef<Empleado> _Empleado;
		
		private EntityRef<Forma_Pago> _Forma_Pago;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_boletaVentaChanging(int value);
    partial void Oncodigo_boletaVentaChanged();
    partial void Oncodigo_encargadoChanging(System.Nullable<int> value);
    partial void Oncodigo_encargadoChanged();
    partial void Oncodigo_formaPagoChanging(System.Nullable<int> value);
    partial void Oncodigo_formaPagoChanged();
    partial void Oncodigo_empleadoChanging(System.Nullable<int> value);
    partial void Oncodigo_empleadoChanged();
    partial void Onfecha_boletaVentaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_boletaVentaChanged();
    partial void OnrtnChanging(string value);
    partial void OnrtnChanged();
    #endregion
		
		public Boleta_Venta()
		{
			this._detalle_boletaVenta = new EntitySet<detalle_boletaVenta>(new Action<detalle_boletaVenta>(this.attach_detalle_boletaVenta), new Action<detalle_boletaVenta>(this.detach_detalle_boletaVenta));
			this._Encargado = default(EntityRef<Encargado>);
			this._Empleado = default(EntityRef<Empleado>);
			this._Forma_Pago = default(EntityRef<Forma_Pago>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_boletaVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_boletaVenta
		{
			get
			{
				return this._codigo_boletaVenta;
			}
			set
			{
				if ((this._codigo_boletaVenta != value))
				{
					this.Oncodigo_boletaVentaChanging(value);
					this.SendPropertyChanging();
					this._codigo_boletaVenta = value;
					this.SendPropertyChanged("codigo_boletaVenta");
					this.Oncodigo_boletaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_encargado", DbType="Int")]
		public System.Nullable<int> codigo_encargado
		{
			get
			{
				return this._codigo_encargado;
			}
			set
			{
				if ((this._codigo_encargado != value))
				{
					if (this._Encargado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_encargadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_encargado = value;
					this.SendPropertyChanged("codigo_encargado");
					this.Oncodigo_encargadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_formaPago", DbType="Int")]
		public System.Nullable<int> codigo_formaPago
		{
			get
			{
				return this._codigo_formaPago;
			}
			set
			{
				if ((this._codigo_formaPago != value))
				{
					if (this._Forma_Pago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_formaPagoChanging(value);
					this.SendPropertyChanging();
					this._codigo_formaPago = value;
					this.SendPropertyChanged("codigo_formaPago");
					this.Oncodigo_formaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_empleado", DbType="Int")]
		public System.Nullable<int> codigo_empleado
		{
			get
			{
				return this._codigo_empleado;
			}
			set
			{
				if ((this._codigo_empleado != value))
				{
					if (this._Empleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_empleadoChanging(value);
					this.SendPropertyChanging();
					this._codigo_empleado = value;
					this.SendPropertyChanged("codigo_empleado");
					this.Oncodigo_empleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_boletaVenta", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_boletaVenta
		{
			get
			{
				return this._fecha_boletaVenta;
			}
			set
			{
				if ((this._fecha_boletaVenta != value))
				{
					this.Onfecha_boletaVentaChanging(value);
					this.SendPropertyChanging();
					this._fecha_boletaVenta = value;
					this.SendPropertyChanged("fecha_boletaVenta");
					this.Onfecha_boletaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rtn", DbType="VarChar(50)")]
		public string rtn
		{
			get
			{
				return this._rtn;
			}
			set
			{
				if ((this._rtn != value))
				{
					this.OnrtnChanging(value);
					this.SendPropertyChanging();
					this._rtn = value;
					this.SendPropertyChanged("rtn");
					this.OnrtnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boleta_Venta_detalle_boletaVenta", Storage="_detalle_boletaVenta", ThisKey="codigo_boletaVenta", OtherKey="codigo_boletaVenta")]
		public EntitySet<detalle_boletaVenta> detalle_boletaVenta
		{
			get
			{
				return this._detalle_boletaVenta;
			}
			set
			{
				this._detalle_boletaVenta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Encargado_Boleta_Venta", Storage="_Encargado", ThisKey="codigo_encargado", OtherKey="codigo_encargado", IsForeignKey=true)]
		public Encargado Encargado
		{
			get
			{
				return this._Encargado.Entity;
			}
			set
			{
				Encargado previousValue = this._Encargado.Entity;
				if (((previousValue != value) 
							|| (this._Encargado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Encargado.Entity = null;
						previousValue.Boleta_Venta.Remove(this);
					}
					this._Encargado.Entity = value;
					if ((value != null))
					{
						value.Boleta_Venta.Add(this);
						this._codigo_encargado = value.codigo_encargado;
					}
					else
					{
						this._codigo_encargado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Encargado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empleado_Boleta_Venta", Storage="_Empleado", ThisKey="codigo_empleado", OtherKey="codigo_empleado", IsForeignKey=true)]
		public Empleado Empleado
		{
			get
			{
				return this._Empleado.Entity;
			}
			set
			{
				Empleado previousValue = this._Empleado.Entity;
				if (((previousValue != value) 
							|| (this._Empleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empleado.Entity = null;
						previousValue.Boleta_Venta.Remove(this);
					}
					this._Empleado.Entity = value;
					if ((value != null))
					{
						value.Boleta_Venta.Add(this);
						this._codigo_empleado = value.codigo_empleado;
					}
					else
					{
						this._codigo_empleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Empleado");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Forma_Pago_Boleta_Venta", Storage="_Forma_Pago", ThisKey="codigo_formaPago", OtherKey="codigo_formaPago", IsForeignKey=true)]
		public Forma_Pago Forma_Pago
		{
			get
			{
				return this._Forma_Pago.Entity;
			}
			set
			{
				Forma_Pago previousValue = this._Forma_Pago.Entity;
				if (((previousValue != value) 
							|| (this._Forma_Pago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Forma_Pago.Entity = null;
						previousValue.Boleta_Venta.Remove(this);
					}
					this._Forma_Pago.Entity = value;
					if ((value != null))
					{
						value.Boleta_Venta.Add(this);
						this._codigo_formaPago = value.codigo_formaPago;
					}
					else
					{
						this._codigo_formaPago = default(Nullable<int>);
					}
					this.SendPropertyChanged("Forma_Pago");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Boleta_Venta = this;
		}
		
		private void detach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Boleta_Venta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalle_boletaVenta")]
	public partial class detalle_boletaVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_boletaVenta;
		
		private int _codigo_alumno;
		
		private int _codigo_servicio;
		
		private int _codigo_PeriodoGrado;
		
		private System.Nullable<double> _precio_servicio;
		
		private EntityRef<Alumno> _Alumno;
		
		private EntityRef<Boleta_Venta> _Boleta_Venta;
		
		private EntityRef<Tipo_ServicioPaga> _Tipo_ServicioPaga;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_boletaVentaChanging(int value);
    partial void Oncodigo_boletaVentaChanged();
    partial void Oncodigo_alumnoChanging(int value);
    partial void Oncodigo_alumnoChanged();
    partial void Oncodigo_servicioChanging(int value);
    partial void Oncodigo_servicioChanged();
    partial void Oncodigo_PeriodoGradoChanging(int value);
    partial void Oncodigo_PeriodoGradoChanged();
    partial void Onprecio_servicioChanging(System.Nullable<double> value);
    partial void Onprecio_servicioChanged();
    #endregion
		
		public detalle_boletaVenta()
		{
			this._Alumno = default(EntityRef<Alumno>);
			this._Boleta_Venta = default(EntityRef<Boleta_Venta>);
			this._Tipo_ServicioPaga = default(EntityRef<Tipo_ServicioPaga>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_boletaVenta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_boletaVenta
		{
			get
			{
				return this._codigo_boletaVenta;
			}
			set
			{
				if ((this._codigo_boletaVenta != value))
				{
					if (this._Boleta_Venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_boletaVentaChanging(value);
					this.SendPropertyChanging();
					this._codigo_boletaVenta = value;
					this.SendPropertyChanged("codigo_boletaVenta");
					this.Oncodigo_boletaVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_alumno", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_alumno
		{
			get
			{
				return this._codigo_alumno;
			}
			set
			{
				if ((this._codigo_alumno != value))
				{
					if (this._Alumno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_alumnoChanging(value);
					this.SendPropertyChanging();
					this._codigo_alumno = value;
					this.SendPropertyChanged("codigo_alumno");
					this.Oncodigo_alumnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_servicio", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_servicio
		{
			get
			{
				return this._codigo_servicio;
			}
			set
			{
				if ((this._codigo_servicio != value))
				{
					if (this._Tipo_ServicioPaga.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncodigo_servicioChanging(value);
					this.SendPropertyChanging();
					this._codigo_servicio = value;
					this.SendPropertyChanged("codigo_servicio");
					this.Oncodigo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_PeriodoGrado", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codigo_PeriodoGrado
		{
			get
			{
				return this._codigo_PeriodoGrado;
			}
			set
			{
				if ((this._codigo_PeriodoGrado != value))
				{
					this.Oncodigo_PeriodoGradoChanging(value);
					this.SendPropertyChanging();
					this._codigo_PeriodoGrado = value;
					this.SendPropertyChanged("codigo_PeriodoGrado");
					this.Oncodigo_PeriodoGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_servicio", DbType="Float")]
		public System.Nullable<double> precio_servicio
		{
			get
			{
				return this._precio_servicio;
			}
			set
			{
				if ((this._precio_servicio != value))
				{
					this.Onprecio_servicioChanging(value);
					this.SendPropertyChanging();
					this._precio_servicio = value;
					this.SendPropertyChanged("precio_servicio");
					this.Onprecio_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Alumno_detalle_boletaVenta", Storage="_Alumno", ThisKey="codigo_alumno", OtherKey="codigo_alumno", IsForeignKey=true)]
		public Alumno Alumno
		{
			get
			{
				return this._Alumno.Entity;
			}
			set
			{
				Alumno previousValue = this._Alumno.Entity;
				if (((previousValue != value) 
							|| (this._Alumno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Alumno.Entity = null;
						previousValue.detalle_boletaVenta.Remove(this);
					}
					this._Alumno.Entity = value;
					if ((value != null))
					{
						value.detalle_boletaVenta.Add(this);
						this._codigo_alumno = value.codigo_alumno;
					}
					else
					{
						this._codigo_alumno = default(int);
					}
					this.SendPropertyChanged("Alumno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Boleta_Venta_detalle_boletaVenta", Storage="_Boleta_Venta", ThisKey="codigo_boletaVenta", OtherKey="codigo_boletaVenta", IsForeignKey=true)]
		public Boleta_Venta Boleta_Venta
		{
			get
			{
				return this._Boleta_Venta.Entity;
			}
			set
			{
				Boleta_Venta previousValue = this._Boleta_Venta.Entity;
				if (((previousValue != value) 
							|| (this._Boleta_Venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Boleta_Venta.Entity = null;
						previousValue.detalle_boletaVenta.Remove(this);
					}
					this._Boleta_Venta.Entity = value;
					if ((value != null))
					{
						value.detalle_boletaVenta.Add(this);
						this._codigo_boletaVenta = value.codigo_boletaVenta;
					}
					else
					{
						this._codigo_boletaVenta = default(int);
					}
					this.SendPropertyChanged("Boleta_Venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_ServicioPaga_detalle_boletaVenta", Storage="_Tipo_ServicioPaga", ThisKey="codigo_servicio", OtherKey="codigo_servicio", IsForeignKey=true)]
		public Tipo_ServicioPaga Tipo_ServicioPaga
		{
			get
			{
				return this._Tipo_ServicioPaga.Entity;
			}
			set
			{
				Tipo_ServicioPaga previousValue = this._Tipo_ServicioPaga.Entity;
				if (((previousValue != value) 
							|| (this._Tipo_ServicioPaga.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tipo_ServicioPaga.Entity = null;
						previousValue.detalle_boletaVenta.Remove(this);
					}
					this._Tipo_ServicioPaga.Entity = value;
					if ((value != null))
					{
						value.detalle_boletaVenta.Add(this);
						this._codigo_servicio = value.codigo_servicio;
					}
					else
					{
						this._codigo_servicio = default(int);
					}
					this.SendPropertyChanged("Tipo_ServicioPaga");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tipo_ServicioPaga")]
	public partial class Tipo_ServicioPaga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_servicio;
		
		private string _descripcion_servicio;
		
		private System.Nullable<double> _precio_servicio;
		
		private EntitySet<detalle_boletaVenta> _detalle_boletaVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_servicioChanging(int value);
    partial void Oncodigo_servicioChanged();
    partial void Ondescripcion_servicioChanging(string value);
    partial void Ondescripcion_servicioChanged();
    partial void Onprecio_servicioChanging(System.Nullable<double> value);
    partial void Onprecio_servicioChanged();
    #endregion
		
		public Tipo_ServicioPaga()
		{
			this._detalle_boletaVenta = new EntitySet<detalle_boletaVenta>(new Action<detalle_boletaVenta>(this.attach_detalle_boletaVenta), new Action<detalle_boletaVenta>(this.detach_detalle_boletaVenta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_servicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_servicio
		{
			get
			{
				return this._codigo_servicio;
			}
			set
			{
				if ((this._codigo_servicio != value))
				{
					this.Oncodigo_servicioChanging(value);
					this.SendPropertyChanging();
					this._codigo_servicio = value;
					this.SendPropertyChanged("codigo_servicio");
					this.Oncodigo_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_servicio", DbType="VarChar(30)")]
		public string descripcion_servicio
		{
			get
			{
				return this._descripcion_servicio;
			}
			set
			{
				if ((this._descripcion_servicio != value))
				{
					this.Ondescripcion_servicioChanging(value);
					this.SendPropertyChanging();
					this._descripcion_servicio = value;
					this.SendPropertyChanged("descripcion_servicio");
					this.Ondescripcion_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_servicio", DbType="Float")]
		public System.Nullable<double> precio_servicio
		{
			get
			{
				return this._precio_servicio;
			}
			set
			{
				if ((this._precio_servicio != value))
				{
					this.Onprecio_servicioChanging(value);
					this.SendPropertyChanging();
					this._precio_servicio = value;
					this.SendPropertyChanged("precio_servicio");
					this.Onprecio_servicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tipo_ServicioPaga_detalle_boletaVenta", Storage="_detalle_boletaVenta", ThisKey="codigo_servicio", OtherKey="codigo_servicio")]
		public EntitySet<detalle_boletaVenta> detalle_boletaVenta
		{
			get
			{
				return this._detalle_boletaVenta;
			}
			set
			{
				this._detalle_boletaVenta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_ServicioPaga = this;
		}
		
		private void detach_detalle_boletaVenta(detalle_boletaVenta entity)
		{
			this.SendPropertyChanging();
			entity.Tipo_ServicioPaga = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Forma_Pago")]
	public partial class Forma_Pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigo_formaPago;
		
		private string _descripcion_formaPago;
		
		private EntitySet<Boleta_Venta> _Boleta_Venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncodigo_formaPagoChanging(int value);
    partial void Oncodigo_formaPagoChanged();
    partial void Ondescripcion_formaPagoChanging(string value);
    partial void Ondescripcion_formaPagoChanged();
    #endregion
		
		public Forma_Pago()
		{
			this._Boleta_Venta = new EntitySet<Boleta_Venta>(new Action<Boleta_Venta>(this.attach_Boleta_Venta), new Action<Boleta_Venta>(this.detach_Boleta_Venta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_formaPago", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigo_formaPago
		{
			get
			{
				return this._codigo_formaPago;
			}
			set
			{
				if ((this._codigo_formaPago != value))
				{
					this.Oncodigo_formaPagoChanging(value);
					this.SendPropertyChanging();
					this._codigo_formaPago = value;
					this.SendPropertyChanged("codigo_formaPago");
					this.Oncodigo_formaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_formaPago", DbType="VarChar(50)")]
		public string descripcion_formaPago
		{
			get
			{
				return this._descripcion_formaPago;
			}
			set
			{
				if ((this._descripcion_formaPago != value))
				{
					this.Ondescripcion_formaPagoChanging(value);
					this.SendPropertyChanging();
					this._descripcion_formaPago = value;
					this.SendPropertyChanged("descripcion_formaPago");
					this.Ondescripcion_formaPagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Forma_Pago_Boleta_Venta", Storage="_Boleta_Venta", ThisKey="codigo_formaPago", OtherKey="codigo_formaPago")]
		public EntitySet<Boleta_Venta> Boleta_Venta
		{
			get
			{
				return this._Boleta_Venta;
			}
			set
			{
				this._Boleta_Venta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Forma_Pago = this;
		}
		
		private void detach_Boleta_Venta(Boleta_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Forma_Pago = null;
		}
	}
}
#pragma warning restore 1591
